export const EVENTS = {
  connection: 'connection',
  CLIENT: {
    SETUP: 'SETUP',
    JOIN_CHAT: 'JOIN_CHAT',
    START_TYPING: 'START_TYPING',
    STOP_TYPING: 'STOP_TYPING',
    SEND_MESSAGE: 'SEND_MESSAGE',
    CREATE_CHAT: 'CREATE_CHAT'
  },
  SERVER: {
    CONNECTED: 'CONNECTED',
    RECEIVED_MESSAGE: 'RECEIVED_MESSAGE',
    STARTED_TYPING: 'STARTED_TYPING',
    STOPPED_TYPING: 'STOPPED_TYPING',
    CREATED_CHAT: 'CREATED_CHAT'
  }
}
